# Generated by Django 3.1.7 on 2021-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='poster',
            field=models.ImageField(null=True, upload_to='cinema_images/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='temporary', upload_to='movie_posters/', verbose_name='پوستر'),
            preserve_default=False,
        ),
    ]
